### PR TITLE
TBF Header Permissions

### PR DESCRIPTION
**Pull request by alistair23**
See: https://github.com/tock/tock/pull/2172 for more details

### CODE REVIEW

**Comment by alistair23** [comment]
Now that https://github.com/tock/tock/pull/2172 has been merged this is ready to go. I have updated this to handle the changes in https://github.com/tock/tock/pull/2172

**Comment by bradjc** [comment]
Is the interface `elf2tab --permissions 0x1,1 --permissions 0x1,2 --permissions 0x4001,0`?

**Comment by alistair23** [comment]
No, it's `--permissions 0,0 0,1 0,2 0,3 0,4 2,0 2,1 2,2 2,3 --verbose`

**Comment by alistair23** [comment]
Which can be auto generated, see here for doing it in libtock-rs: https://github.com/tock/libtock-rs/pull/300

**Comment by alistair23** [comment]
Ping!

**Comment by alistair23** [comment]
Ping!

**Review by bradjc — APPROVED** [review]

**Review by ppannuto — APPROVED** [review]

**Pull request merged**
