### PR TITLE
Move from structopt to clap v4

### LINKED ISSUE #53: Update from structopt to clap
[structopt](https://github.com/TeXitoi/structopt) is in maintenance mode and has been replaced by [clap](https://github.com/clap-rs/clap). There is a [migration guide](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating), but it's not just a drop-in replacement.

We should eventually update this, but it's not exactly a rush since it's just command-line argument parsing.

### PR DESCRIPTION
**Pull request by lhvy**
Resolves #53 with minimal changes. Whilst all tests pass and the program seems to function the same, any extra testing would be appreciated to ensure the application functions the same as before.

Please let me know if there are any problems or desired changes!

------

_I'm participating in [Hacktoberfest 2022](https://hacktoberfest.com) and if this PR is approved it, it would be greatly appreciated if the PR could be labelled `hacktoberfest-accepted`, or even the repository labelled as `hacktoberfest` to allow PRs in this repository to count towards the competition!_

### CODE REVIEW

**Comment by bradjc** [comment]
Hm, `elf2tab --version` no longer works.

```
$ elf2tab --version
error: Found argument '--version' which wasn't expected, or isn't valid in this context

	Did you mean '--app-version'?

	If you tried to supply `--version` as a value rather than a flag, use `-- --version`

USAGE:
    elf2tab [FLAGS] [OPTIONS] ELF[,ARCHITECTURE]...
Converts Tock userspace programs from .elf files to Tock Application Bundles.

For more information try --help
```

**Comment by lhvy** [comment]
I'll check on it now, not sure how I missed that...

**Comment by lhvy** [comment]
All fixed now. Nice catch! Did you spot anything else I may have missed?

**Comment by bradjc** [comment]
Something still wrong:

```
$ elf2tab --app-version 7 --sha256 --sha512 --rsa4096-private /Users/bradjc/git/elf2tab/tockkey.private.der --rsa4096-public /Users/bradjc/git/elf2tab/tockkey.public.der --write_id 48877 --read_ids 4 5 9 88 --access_ids 111 -n blink --stack 2048 --app-heap 1024 --kernel-heap 1024 --kernel-major 2 --kernel-minor 0 -v -o build/blink.tab build/cortex-m0/cortex-m0.elf build/cortex-m3/cortex-m3.elf build/cortex-m4/cortex-m4.elf build/cortex-m7/cortex-m7.elf
thread 'main' panicked at 'Could not open the .elf file.: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:76:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [build/blink.tab] Error 101
```

**Comment by lhvy** [comment]
Ok this is embarrassing... I've been sitting on these changes for a few days now, and it seems in that time, clap v4 released. If you want to hold on to this PR for a bit, I'll update to clap v4 for you.

**Comment by bradjc** [comment]
No problem! Thanks for the help.

**Comment by lhvy** [comment]
> Something still wrong:
> 
> ```
> $ elf2tab --app-version 7 --sha256 --sha512 --rsa4096-private /Users/bradjc/git/elf2tab/tockkey.private.der --rsa4096-public /Users/bradjc/git/elf2tab/tockkey.public.der --write_id 48877 --read_ids 4 5 9 88 --access_ids 111 -n blink --stack 2048 --app-heap 1024 --kernel-heap 1024 --kernel-major 2 --kernel-minor 0 -v -o build/blink.tab build/cortex-m0/cortex-m0.elf build/cortex-m3/cortex-m3.elf build/cortex-m4/cortex-m4.elf build/cortex-m7/cortex-m7.elf
> thread 'main' panicked at 'Could not open the .elf file.: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:76:60
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> make: *** [build/blink.tab] Error 101
> ```

I think I've made some progress on this one, would you be able to send a link to those .elf files so I can test the same command as you? I have my RSA key pair made already.

**Comment by bradjc** [comment]
https://www.dropbox.com/s/etkk9ggjyeowj5y/cortex-m0.elf?dl=0
https://www.dropbox.com/s/zxtbk6qr57ut73z/cortex-m4.elf?dl=0

Two should be enough to test

**Comment by lhvy** [comment]
Ok this looks better, is fully up to date, and has no deprecation warnings! 🎉

The sample line you sent me worked perfectly with the provided files, so I'd be fairly confident now. Feel free to test as much as you want first, and I'd 100% recommend reading through my changes carefully as clap v4 required I put some more explicit validation on inputs, particularly with `Vec<T>` arguments.

clap v4 seems to have (at least temporarily) swapped from using color in the help command to bold, italics and underlined text. [More info here.](https://epage.github.io/blog/2022/09/clap4/#polishing-help-output) It'd also be great if you could make sure you're ok with that. Here's what the output looks like in my terminal:
image

**Comment by lhvy** [comment]
At this point, if you're happy with the changes and functionality seems fine to you as well, I'm happy to stop working on this and let you merge the branch when you're ready.

**Comment by bradjc** [comment]
> clap v4 seems to have (at least temporarily) swapped from using color in the help command to bold, italics and underlined text. [More info here.](https://epage.github.io/blog/2022/09/clap4/#polishing-help-output) It'd also be great if you could make sure you're ok with that. Here's what the output looks like in my terminal:

I personally don't care, I would prefer to be consistent with the larger rust community.

**Review by brghena — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Review by hudson-ayers — APPROVED** [review]

**Comment by hudson-ayers** [comment]
> I also have another branch that fixes a lot of clippy warnings I was receiving whilst working on this repo if you're interested in that.

I would like to see a PR with these fixes. What might be even better is a PR with those fixes that also enforces in CI that clippy should pass. I will note that we probably do not want all clippy lints to be enforced -- the clippy options we use for the main tock repo might be a good starting point: https://github.com/tock/tock/blob/master/tools/run_clippy.sh

**Pull request merged**
